import type { ImageMetadata } from 'astro';
/** Photography from the current owt.com.ua, colour-graded for a consistent look. */
import aerialIsland from '../assets/photos/aerial-island.jpg';
import aerialMarina from '../assets/photos/aerial-marina.jpg';
import shoreline from '../assets/photos/shoreline.jpg';
import aerialIslandPortrait from '../assets/photos/aerial-island-portrait.jpg';
import aerialMarinaPortrait from '../assets/photos/aerial-marina-portrait.jpg';
import shorelinePortrait from '../assets/photos/shoreline-portrait.jpg';
import marinaPier from '../assets/photos/marina-pier.jpg';
import riprap from '../assets/photos/riprap.jpg';
import longreach from '../assets/photos/longreach.jpg';
import treeLift from '../assets/photos/tree-lift.jpg';
import pierGangway from '../assets/photos/pier-gangway.jpg';
import dredging from '../assets/photos/dredging.jpg';
import poolPontoons from '../assets/photos/pool-pontoons.jpg';
import treeHead from '../assets/photos/tree-head.jpg';
import jcbShore from '../assets/photos/jcb-shore.jpg';
import jcbPair from '../assets/photos/jcb-pair.jpg';
import marinaAerial from '../assets/photos/marina-aerial.jpg';
import pontoonsConcrete from '../assets/photos/pontoons-concrete.jpg';
// Project series — generated by scripts/prepare-projects.mjs (shared crop + grade)
import projShore from '../assets/projects/shore-concrete-pontoons.jpg';
import projYacht from '../assets/projects/yacht-club.jpg';
import projTrees from '../assets/projects/tree-transplanting.jpg';
import projPiers from '../assets/projects/piers.jpg';

export const media = {
  aerialIsland,
  aerialMarina,
  shoreline,
  marinaPier,
  riprap,
  longreach,
  treeLift,
  pierGangway,
  dredging,
  poolPontoons,
  treeHead,
  jcbShore,
  jcbPair,
  marinaAerial,
  pontoonsConcrete,
  projShore,
  projYacht,
  projTrees,
  projPiers,
};

export type MediaKey = keyof typeof media;

/** Phone (portrait) art direction for full-screen hero frames. */
export const portraitOf: Partial<Record<MediaKey, ImageMetadata>> = {
  aerialIsland: aerialIslandPortrait,
  aerialMarina: aerialMarinaPortrait,
  shoreline: shorelinePortrait,
};
